### ISSUE TITLE
Certificate.sha256Hash method

### ISSUE THREAD

**Issue by yschimke** [cashapp/certifikit#15]
It would be good to have an equivelant to the CertificatePinner method, but I'm missing something obvious when try to implement, or the encoding isn't matching exactly?

```
    fun X509Certificate.sha256Hash(): ByteString =
      publicKey.encoded.toByteString().sha256()
```

**Comment by swankjesse** [comment]
I think you want to hash the encoded subjectPublicKeyInfo.

**Comment by yschimke** [comment]
https://github.com/cashapp/certifikit/pull/16

**Comment by yschimke** [comment]
TODO rename

**Comment by yschimke** [comment]
Also https://github.com/cashapp/certifikit/pull/24
