### ISSUE TITLE
Move nativeImage build into gradle using palantir plugin

### ISSUE THREAD

**Issue by yschimke** [cashapp/certifikit#28]
See https://github.com/yschimke/okurl/blob/master/build.gradle.kts#L161-L177

**Comment by JakeWharton** [comment]
I used https://github.com/palantir/gradle-graal a year or three ago. Seems to still be working and maintained.

**Comment by yschimke** [comment]
+1 I've used it before but stopped because it didn't cleanly support version 20, but it now does.  And it kept filling up the disk of my personal laptop particularly when verion changes happened e.g. .\.gradle\caches\com.palantir.graal\20.1.0\8\graalvm-ce-java8-20.1.0-amd64.zip

**Comment by yschimke** [comment]
@JakeWharton ok ok, solid advice

https://github.com/cashapp/certifikit/pull/32
